name: klusterthon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  icons_plus: ^4.0.0
  flutter_zoom_drawer: "3.1.1"
  dio: ^5.3.4
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.2.0
  flutter_easyloading: ^3.0.5
  easy_loading_button: ^0.3.2
  loading_animation_widget: ^1.2.0+4
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  reactive_forms_generator: ^4.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
