name: col23

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
        with:
          token: ${{ secrets.DEPLOY }}
      - uses: subosito/flutter-action@v1
      - uses: AlienKevin/flutter-gh-pages@v11
        with:
          targetBranch: main
          webRenderer: canvaskit
